const MOCKDATA = [
  {
    userImage: '',
    userName: 'JohnDoe',
    term: 1,
    date: '2024-04-19',
    content: 'Just another day at work!',
    emojiCount: 3,
    commentCount: 10,
    eyeCount: 50,
  },
  {
    userImage: '',
    userName: 'JaneSmith',
    term: 2,
    date: '2024-04-18',
    content: 'Exploring new places. #Travel',
    image: 'travel.jpg',
    emojiCount: 5,
    commentCount: 15,
    eyeCount: 75,
  },
  {
    userImage: '',
    userName: 'MikeJohnson',
    term: 3,
    date: '2024-04-17',
    content: 'Coding all day! #DeveloperLife',
    emojiCount: 2,
    commentCount: 8,
    eyeCount: 40,
  },
  {
    userImage: '',
    userName: 'EmilyBrown',
    term: 4,
    date: '2024-04-16',
    content: 'Chilling with friends. #WeekendVibes',
    image: 'friends.jpg',
    emojiCount: 4,
    commentCount: 12,
    eyeCount: 60,
  },
  {
    userImage: '',
    userName: 'ChrisTaylor',
    term: 5,
    date: '2024-04-15',
    content: 'Reading a new book. #Bookworm',
    emojiCount: 1,
    commentCount: 6,
    eyeCount: 30,
  },
  {
    userImage: '',
    userName: 'AmandaClark',
    term: 6,
    date: '2024-04-14',
    content: 'Cooking up a storm in the kitchen!',
    image: 'cooking.jpg',
    emojiCount: 3,
    commentCount: 9,
    eyeCount: 45,
  },
  {
    userImage: '',
    userName: 'MichaelSmith',
    term: 7,
    date: '2024-04-13',
    content: 'Solving puzzles is my favorite hobby. #PuzzleMaster',
    emojiCount: 2,
    commentCount: 7,
    eyeCount: 35,
  },
  {
    userImage: '',
    userName: 'SarahJohnson',
    term: 8,
    date: '2024-04-12',
    content: 'Enjoying a cup of coffee on a rainy day.',
    image: 'coffee.jpg',
    emojiCount: 4,
    commentCount: 11,
    eyeCount: 55,
  },
  // {
  //   userImage: '',
  //   userName: 'AlexBrown',
  //   term: 9,
  //   date: '2024-04-11',
  //   content: 'Hiking in the mountains. #NatureLover',
  //   image: 'hiking.jpg',
  //   emojiCount: 3,
  //   commentCount: 10,
  //   eyeCount: 50,
  // },
  // {
  //   userImage: '',
  //   userName: 'EmmaDavis',
  //   term: 10,
  //   date: '2024-04-10',
  //   content: 'Listening to my favorite music playlist.',
  //   emojiCount: 2,
  //   commentCount: 8,
  //   eyeCount: 40,
  // },
  // {
  //   userImage: '',
  //   userName: 'DanielWilson',
  //   term: 11,
  //   date: '2024-04-09',
  //   content: 'Feeling productive today! #WorkLife',
  //   emojiCount: 3,
  //   commentCount: 9,
  //   eyeCount: 45,
  // },
  // {
  //   userImage: '',
  //   userName: 'OliviaMartinez',
  //   term: 12,
  //   date: '2024-04-08',
  //   content: 'Binge-watching my favorite TV series.',
  //   image: 'tv_series.jpg',
  //   emojiCount: 5,
  //   commentCount: 15,
  //   eyeCount: 75,
  // },
  // {
  //   userImage: '',
  //   userName: 'WilliamBrown',
  //   term: 13,
  //   date: '2024-04-07',
  //   content: 'Gardening in my backyard. #GreenThumb',
  //   image: 'gardening.jpg',
  //   emojiCount: 2,
  //   commentCount: 7,
  //   eyeCount: 35,
  // },
  // {
  //   userImage: '',
  //   userName: 'SophiaWilson',
  //   term: 14,
  //   date: '2024-04-06',
  //   content: 'Trying out a new recipe. #Foodie',
  //   image: 'recipe.jpg',
  //   emojiCount: 4,
  //   commentCount: 12,
  //   eyeCount: 60,
  // },
  // {
  //   userImage: '',
  //   userName: 'EthanThomas',
  //   term: 15,
  //   date: '2024-04-05',
  //   content: 'Playing video games with friends.',
  //   image: 'gaming.jpg',
  //   emojiCount: 3,
  //   commentCount: 9,
  //   eyeCount: 45,
  // },
  // {
  //   userImage: '',
  //   userName: 'MiaGarcia',
  //   term: 16,
  //   date: '2024-04-04',
  //   content: 'Enjoying a sunset at the beach. #Relaxation',
  //   image: 'beach.jpg',
  //   emojiCount: 5,
  //   commentCount: 15,
  //   eyeCount: 75,
  // },
  // {
  //   userImage: '',
  //   userName: 'DavidLopez',
  //   term: 17,
  //   date: '2024-04-03',
  //   content: 'Attending a music concert. #MusicLover',
  //   image: 'concert.jpg',
  //   emojiCount: 2,
  //   commentCount: 8,
  //   eyeCount: 40,
  // },
];

export default MOCKDATA;
